config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  root to: 'index#index'

  get 'about-us', to: 'about#index'
  get '/about-us/history', to: 'about#history'
  get '/about-us/contact', to: 'about#contact'
  get '/about-us/governance', to: 'about#governance'
  get '/about-us/community', to: 'about#community'

  get 'membership', to: 'membership#index'
  get 'membership/join', to: 'membership#join'
  get 'membership/get-involved', to: 'membership#get_involved'
  get 'membership/rules', to: 'membership#rules'

  get 'community', to: 'community#index'
  get 'community/social', to: 'community#social'
  get 'community/volunteer', to: 'community#volunteer'

  get 'classes', to: 'about#classes'

  get 'blog',        to: 'interior#blog_archive'
  get 'blog/post', to: 'interior#blog_detail'
  get 'legalese',    to: 'index#legalese'

  resources :events

  namespace :dashboard do
    root to: 'overview#show'
    resources :events
    resources :members
    resource :profile
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  before_create :set_unique_identifiers

  protected

  def generate_username
    candidate = full_name.sub('.', ' ').gsub(/\s+/, '.').downcase
    return candidate unless Member.exists?(lab_username: candidate)

    counter = 2
    while Member.exists?(lab_username: "#{candidate}.#{counter}")
      counter += 1
    end

    "#{candidate}.#{counter}"
  end

  def set_unique_identifiers
    self.lab_username = generate_username unless lab_username
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  layout 'brochure'
  before_action :initialize_breadcrumbs

  def index
    active_leftnav_item :main
  end

  def community
    active_leftnav_item :community
    push_breadcrumb('Community', 'about-us/community')
  end

  def history
    active_leftnav_item :history
    push_breadcrumb('History', '/about-us/history')
  end

  def contact
    active_leftnav_item :contact
    push_breadcrumb('Location and Contact Info', '/about-us/contact')
  end

  def governance
    active_leftnav_item :governance
    push_breadcrumb('Governance', '/about-us/governance')
  end

  protected

  def initialize_breadcrumbs
    push_breadcrumb('About Us', '/about-us')

    add_leftnav_item(:main, 'Who We Are', '/about-us')
    add_leftnav_item(:community, 'Our Community', '/about-us/community')
    add_leftnav_item(:history, 'History', '/about-us/history')
    add_leftnav_item(:contact, 'Contact/Visit Us', '/about-us/contact')
    add_leftnav_item(:governance, 'Governance', '/about-us/governance')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource
  before_action :create_breadcrumbs_array
  before_action :create_leftnav_array

  protected

  def layout_by_resource
    return 'auth' if devise_controller?
    return 'application'
  end

  def push_breadcrumb(title, path)
    crumb = OpenStruct.new
    crumb.title = title
    crumb.path = path
    @breadcrumbs << crumb
  end

  def create_breadcrumbs_array
    @breadcrumbs = []
    push_breadcrumb('Home', root_path)
  end

  def create_leftnav_array
    @leftnav_items = []
    @leftnav_items_hash = {}
  end

  def add_leftnav_item(key, name, path)
    item = OpenStruct.new
    item.active = false
    item.name = name
    item.path = path
    @leftnav_items << item
    @leftnav_items_hash[key] = item
  end

  def active_leftnav_item(key)
    @leftnav_items.each {|i| i.active = false }
    @leftnav_items_hash[key].active = true
  end
end

app/controllers/dashboard/abstract_dashboard_controller.rb
module Dashboard
  class AbstractDashboardController < ApplicationController
    layout 'dashboard'
    before_action :authenticate_member!
  end
end

app/controllers/dashboard/events_controller.rb
module Dashboard
  class EventsController < AbstractDashboardController
  end
end

app/controllers/dashboard/members_controller.rb
module Dashboard
  class MembersController < AbstractDashboardController
    before_action :find_member, except: [:create, :index]

    def index
      @members = Member.all
    end

    def show; end

    def update; end

    protected

    def find_member
      return @member unless @member.nil?
      if params['id'] == 'me'
        @member = current_member
      else
        @member = Member.find(params[:id])
      end
      @member
    end
  end
end

app/controllers/dashboard/overview_controller.rb
module Dashboard
  class OverviewController < AbstractDashboardController
    def show; end
  end
end

app/controllers/dashboard/profiles_controller.rb
module Dashboard
  class ProfilesController < AbstractDashboardController
    def show
      @profile = current_member
    end

    def update
      @profile = current_member
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout 'inner'
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index;end
end

app/controllers/interior_controller.rb
class InteriorController < ApplicationController
  layout 'inner'

  def blog_archive
    @posts = fake_posts
  end

  def blog_detail
    @post = fake_post
    @sidebar_posts = fake_posts(3)
  end

  protected

  def fake_post
    p = OpenStruct.new
    p.title = Faker::Hipster.sentence.chomp('.')
    p.author = Faker::StarTrek.character
    p.date = rand(2930).days.ago
    p.excerpt = Faker::Hipster.paragraphs(1).join(' ')
    p.body = '<p>' + Faker::Hipster.paragraphs(9, true).join('</p><p>') + '</p>'
    p
  end

  def fake_posts(count=7)
    posts = []
    count.times do
      posts << fake_post
    end
    posts.sort_by { |p| p.date }
  end
end

app/controllers/membership_controller.rb
class MembershipController < ApplicationController
  layout 'brochure'
  before_action :initialize_breadcrumbs

  def index
    active_leftnav_item :main
  end

  def join
    active_leftnav_item :join
    push_breadcrumb 'How to Join', '/membership/join'
  end

  def get_involved
    active_leftnav_item :get_involved
    push_breadcrumb 'Getting Involved', '/membership/get-involved'
  end

  def rules
    active_leftnav_item :rules
    push_breadcrumb 'Rules and Policies', '/membership/rules'
  end

  protected

  def initialize_breadcrumbs
    push_breadcrumb('Membership', '/membership')

    add_leftnav_item(:main, 'Benefits', '/membership')
    add_leftnav_item(:join, 'How to Join', '/membership/join')
    add_leftnav_item(:get_involved, 'Getting Involved', '/membership/get-involved')
    add_leftnav_item(:rules, 'Rules and Policies', '/membership/rules')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/about/community.html.erb
<% content_for :page_title do %>
  About Us
<% end %>

<%content_for :hero_image do %>
  <%= image_path('chisels-in-row.jpg') %>
<% end %>

<h2>Our Community</h2>

<p>Twin Cities Maker</p>

app/views/about/contact.html.erb
<% content_for :page_title do %>
  About Us
<% end %>

<%content_for :hero_image do %>
  <%= image_path('chisels-in-row.jpg') %>
<% end %>

<div class="alert alert-dark" role="alert">
  <h4 class="alert-heading">Developer Note</h4>
  We should probably have a contact form, so that people can reach out to us
  more easily. I'm not going to mock that up here, but if we had one we'd probably
  split this page into two: one for the form and one for the map and open house information.
</div>

<h2>Get In Touch</h2>

<p>Our workshop is located in the Seward neighborhood of Minneapolis, and we're
active on a number of online platforms.</p>

<h3>Our Location</h3>

<p>
  We host an open house every Wednesday evening from 7:00 PM to 9:00 PM. During
  that time, you're welcome to stop by, get a tour of the shop, and chat with
  some of our board members.
</p>

<div class="row">
  <div class="col-md-8">
    <%= link_to 'https://www.openstreetmap.org/?mlat=44.95527&mlon=-93.22635#map=19/44.95527/-93.22635' do %>
      <%= image_tag('map-to-hack-factory-16x9.png', class: 'img-fluid') -%>
    <% end %>
  </div>
  <div class="col-md-4">
    <p><strong>Twin Cities Maker</strong><br>
    3119 E. 26th Street<br>
    Minneapolis, MN 55406</p>
  </div>
</div>

app/views/about/governance.html.erb
<% content_for :page_title do %>
  About Us
<% end %>

<%content_for :hero_image do %>
  <%= image_path('chisels-in-row.jpg') %>
<% end %>

<h2>Governance</h2>

<p>Twin Cities Maker</p>

app/views/about/history.html.erb
<% content_for :page_title do %>
 About Us
<% end %>

<%content_for :hero_image do %>
 <%= image_path('chisels-in-row.jpg') %>
<% end %>

<h2>History</h2>

<p>
  Paul Sobszak, electrical engineer, media
  enthusiast, world traveler, musician, and
  consummate maker, launched a Twin
  Cities Maker website on January 6, 2009.
  The community that formed
  through the website forums began to meet
  casually later in January at the Anodyne
  Café and then the Common Roots Café in
  Minneapolis.
</p>

<p>
  During spring and summer of 2009, those
  meet-ups became semi-formal meetings.
  By midsummer a club had been formed to
  start raising funds to incorporate and
  open a small workshop.
</p>

<p>
  In early December 2009, our community
  was approached by another group, the
  recently incorporated Hack Factory of
  Minnesota, who were also seeking to open
  a community workshop. On December
  16th the groups voted unanimously to
  merge and to lease a portion of a space at
  3119 E. 26th Street in Minneapolis.
</p>

<p>
  On January 6th, 2010, a year to the day
  after the original website went up, we
  voted to expand our lease. We decided
  that our physical home would be called
  the "Hack Factory" and our community
  would be known as Twin Cities Maker.
</p>

<p>
  Our first group project was the
  Spoonapult, created for the Science
  Museum of Minnesota's 2009 Make: Day
  exhibition. While we were unable to
  exhibit our scale model of the iconic
  Spoonbridge and Cherry sculpture (which
  is a functional catapult), we had a grand
  time testing it on Raspberry Island, and
  reworked it for a successful demonstration
  at the 2010 Make: Day.
</p>

<p>
  Since that first project, our members have
  created a variety of group projects:
  "Bessie," a cow-headed sea monster and
  crowd favorite at the Aquatennial Milk
  Carton Boat Race, a life-sized
  "Operation" game, a mural for our shop,
  and many other collaborative works.
</p>

app/views/about/index.html.erb
<% content_for :page_title do %>
  About Us
<% end %>

<%content_for :hero_image do %>
  <%= image_path('chisels-in-row.jpg') %>
<% end %>

<h2> Who We Are</h2>

<p>Twin Cities Maker</p>

app/views/dashboard/members/index.html.haml
%h2 Members

%table.table
  %thead
    %tr
      %th{ scope: 'col' } #
      %th{ scope: 'col' } Surname
      %th{ scope: 'col' } Given Name
      %th{ scope: 'col' } CiviCRM Number
      %th{ scope: 'col' } Email
      %th{ scope: 'col' } LDAP
      %th{ scope: 'col' } Created At
      %th{ scope: 'col' } Updated At
  %tbody
    - @members.each do |member|
      %tr
        %th{ scope: 'row' }= link_to member.id, dashboard_member_path(member)
        %td= member.surname
        %td= member.given_name
        %td= member.civicrm_identifier
        %td
          %code= member.email
        %td
          %code= member.lab_username
        %td= member.created_at
        %td= member.updated_at

app/views/dashboard/members/show.html.haml
%h2= @member.full_name

Detailed view of this person

app/views/dashboard/overview/show.html.haml
%h3 Hello Dashboard User

app/views/events/index.html.erb
<%= month_calendar do |date| %>
  <%= date %>
<% end %>

<% content_for :sidebar_content do %>
  rofl
<% end %>

app/views/index/index.html.erb
<div class="jumbotron jumbotron-main">
  <h1 class="display-4">Find Your Creativity</h1>
  <p class="lead">
    Twin Cities Maker is a non-profit, volunteer-driven community of artists, engineers, and
    makers. Together, we operate a shared community workshop
    where you can build nearly anything you can imagine.
  </p>
  <hr class="my-4">
  <a class="btn btn-primary btn-lg" href="/about-us" role="button">Learn More</a>
</div>

<div class="row mb-5">
  <div class="col-lg-4">
    <h3>Make</h3>

    <p>
      Whether you're into in woodworking, metalworking, or high-precision
      machining, we've got the tools, space, and equipment to help your projects
      come together. All of our members have 24-7 access to our workshop.
    </p>

    <p><a class="btn btn-primary" href="/our-workshop">More about our shop</a></p>
  </div>

  <div class="col-lg-4">
    <h3>Share</h3>

    <p>
      More than our workshop and our tools, it's our sense of community that
      makes us who and what we are. If your looking for others who share your
      enthusiasm for building things, fixing things, and figuring out how stuff
      works, you may have just found your people.
    </p>

    <p><a class="btn btn-primary" href="/about-us/community">Learn More</a></p>
  </div>

  <div class="col-lg-4">
    <h3>Learn</h3>

    <p>
      You weren't born knowing how to weld and operate laser cutters, and
      neither were we. We're always offering classes to teach these skills and
      many others.
    </p>

    <p><a class="btn btn-primary" href="/classes">Learn More</a></p>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <h2>From the Blog</h2>
  </div>
</div>
<div class="row">
  <div class="row">
    <!-- begin blog post -->
    <div class="col-lg-6">
      <div class="card flex-md-row blog-preview">
        <div class="card-body d-flex align-items-start">
          <div class="card-text">
            <h3><a href="/blog/post">Grilling! With food! Wednesday night!</a></h3>
            <p class="byline">
              by Bob Poate, October 8th, 2018
            </p>
            <p>They said it couldn’t be done. They said we were foolish to try. But
              Grillchefmeister Michael is planning on doing what doubters said
              couldn’t, nay, shouldn’t be done! Grill outside in the lovely fall
              weather we’re currently experiencing. So come early, come often to the
              Open House Wednesday night, and experience the Thrill of the Grill when
              you can actually use some nice hot food.</p>

              <a href="/blog/post">Continue reading</a>
          </div>
        </div>
        <%= image_tag('chef-pot.png', class: 'card-img-right flex-none') -%>
      </div>
    </div>
    <!-- end -->

    <!-- begin blog post -->
    <div class="col-lg-6">
      <div class="card flex-md-row blog-preview">
        <div class="card-body flex-column">
          <div class="card-text">
            <h3><a href="/blog/post">Big Laser is Ready for Use</a></h3>
            <p class="byline">
              by Samuel L. Jackson, October 4th, 2018
            </p>
            <p>You think water moves fast? You should see ice. It moves like it
              has a mind. Like it knows it killed the world once and got a taste
              for murder. After the avalanche, it took us a week to climb out.
              Now, I don't know exactly when we turned on each other, but I
              know that seven of us survived the slide... and only five made it
              out. Now we took an oath, that I'm breaking now. We said we'd say
              it was the snow that killed the other two, but it wasn't. Nature
              is lethal but it doesn't hold a candle to man.</p>

              <a href="/blog/post">Continue reading</a>
          </div>
          <!-- <%= image_tag('chef-pot.png', class: 'card-img-right flex-auto') -%> -->
        </div>
      </div>
    </div>
    <!-- end -->
  </div>
</div>

app/views/interior/blog_archive.html.erb
<div class="row">
  <% @posts.each do |p| %>
    <div class="card flex-md-row blog-preview">
      <div class="card-body d-flex align-items-start">
        <div class="card-text">
          <h3><a href="/blog/post"><%= p.title %></a></h3>
          <p class="byline">
            by <%= Faker::StarTrek.villain %>, October 8th, 2018
          </p>
          <p>They said it couldn’t be done. They said we were foolish to try. But
            Grillchefmeister Michael is planning on doing what doubters said
            couldn’t, nay, shouldn’t be done! Grill outside in the lovely fall
            weather we’re currently experiencing. So come early, come often to the
            Open House Wednesday night, and experience the Thrill of the Grill when
            you can actually use some nice hot food.</p>

            <a href="/blog/post">Continue reading</a>
        </div>
      </div>
      <img class="card-img-right flex-none blog-preview-image" src="/assets/chef-pot-73c0835ba204cb76c77c992894c7b716112cc8906e6d87b0f0318d5d56b5d0fb.png">
    </div>
  <% end %>
</div>

<% content_for :sidebar_content do %>
  rofl
<% end %>

app/views/interior/blog_detail.html.erb
<% content_for :sidebar_content do %>
  <h3>Other Posts</h3>
  <%- @sidebar_posts.each do |p| %>
    <%= p.title %>
  <% end %>
<% end %>

<% content_for :page_title do %>
  <%= @post.title %>
<% end %>

<% content_for :page_subtitle do %>
  <div class="byline">
    by <a href="#">Samuel L. Jackson</a>, October 4th, 2018
  </div>
<% end %>

<article class="blog-post">
  <%= @post.body.html_safe %>
</article>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <%= render "layouts/partials/head" %>
  <body>
    <div class="container nav-container">
      <%= render 'layouts/partials/top_nav' %>
    </div>
    <div class="container main-container">
      <%= yield %>
    </div>

    <%= render "layouts/partials/footer" %>
  </body>
</html>

app/views/layouts/auth.html.haml
!!! 5
%html
  %head
    %meta{ charset: 'utf-8' }
    %meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge,chrome=1' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'auth', media: 'all'
    = javascript_include_tag 'application'
  %body
    .container.auth-container
      .row
        .col-lg-6.offset-lg-3
          .card
            .card-header
              = yield :page_title
            .card-body
              - # TODO: Flash messages
              - flash.each do |type, message|
                %p= message
              = yield
          %header
            = image_tag('logo-red-text.svg', class: "d-inline-block align-top", alt: "Twin Cities Maker")

app/views/layouts/brochure.html.erb
<!doctype html>
<html lang="en">
  <%= render "layouts/partials/head" %>
  <body>
    <div class="container nav-container">
      <%= render 'layouts/partials/top_nav' %>
    </div>
    <div class="container main-container">

      <%= render "layouts/partials/breadcrumbs" %>

      <!-- <%= yield :hero_image %> -->

      <h1 class="brochure-heading" style="background-image: url(<%= yield :hero_image %>)"><%= yield :page_title %></h1>

      <div class="row">
        <div class="col-md-3 left-nav">
          <ul class="nav flex-column">
            <% @leftnav_items.each do |i| %>
              <li class="nav-item">
                <%= link_to i.name, i.path, class: i.active ? 'nav-link active' : 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>

        <div class="col-md-9">
          <!-- <section class="page-heading">
            <h2><%= yield :page_title %></h2>
            <% if content_for(:page_subtitle) %>
              <%= yield :page_subtitle %>
            <% end %>
          </section> -->
          <%= yield %>
        </div>
      </div>
    </div> <!-- main-container -->
    <%= render "layouts/partials/footer" %>
  </body>
</html>

app/views/layouts/dashboard.html.haml
!!! 5
%html
  %head
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no' }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'dashboard', media: 'all'
    = javascript_include_tag 'application'
    %title Twin Cities Maker
  %body
    = render 'layouts/partials/dashboard/topnav'
    .container-fluid
      .row
        %nav.col-md-2.d-none.d-md-block.bg-light.sidebar
          .sidebar-sticky
            = render 'layouts/partials/dashboard/nav_links'
            = render 'layouts/partials/dashboard/nav_links'
            = render 'layouts/partials/dashboard/nav_links'
        .col-md-9.ml-sm-auto.col-lg-10.px-4
          = yield

app/views/layouts/inner.html.erb
<!doctype html>
<html lang="en">
  <%= render "layouts/partials/head" %>
  <body>
    <div class="container nav-container">
      <%= render 'layouts/partials/top_nav' %>
    </div>
    <div class="container main-container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item"><a href="/blog">Blog</a></li>
          <li class="breadcrumb-item active" aria-current="page">Blog Post</li>
        </ol>
      </nav>
      <section class="page-heading">
        <h2><%= yield :page_title %></h2>
        <% if content_for(:page_subtitle) %>
          <%= yield :page_subtitle %>
        <% end %>
      </section>
      <div class="row">
        <div class="col-md-8">
          <%= yield %>
        </div>
        <div class="col-md-3 offset-md-1">
          <form>
            <div class="input-group mb-3">
              <input type="text" class="form-control" placeholder="search terms" aria-label="Search the blog" aria-describedby="button-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button" id="button-addon2">Search</button>
              </div>
            </div>
          </form><br>
          <%= yield :sidebar_content %>
        </div>
      </div>
    </div>
    <%= render "layouts/partials/footer" %>
  </body>
</html>

app/views/layouts/partials/_breadcrumbs.html.erb
<% unless @breadcrumbs.empty? %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <% *inactive_breadcrumbs, active_breadcrumb = @breadcrumbs %>
      <% inactive_breadcrumbs.each do |b| %>
        <li class="breadcrumb-item"><%= link_to b.title, b.path %></li>
      <% end %>
      <li class="breadcrumb-item active" aria-current="page"><%= active_breadcrumb.title %></li>
    </ol>
  </nav>
<% end %>

app/views/layouts/partials/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= link_to 'https://www.openstreetmap.org/?mlat=44.95527&mlon=-93.22635#map=19/44.95527/-93.22635' do %>
          <%= image_tag('map-to-hack-factory.png', class: 'img-fluid') -%>
        <% end %>
      </div>

      <div class="col-md-3">
        <h6>Our Location</h6>
        <p>3119 E. 26th Street<br>
        Minneapolis, MN 55406</p>

        <h6>Contact Information</h6>
        <p>lol</p>

      </div>

      <div class="col-md-3">
        <h6>Follow Us</h6>
        <ul class="list-unstyled">
          <li><a href="https://tcmaker.eventbrite.com/">EventBrite</a></li>
          <li><a href="https://www.facebook.com/groups/85060647690/">Facebook</a></li>
          <li><a href="https://github.com/tcmaker">GitHub</a></li>
          <li><a href="https://groups.google.com/forum/#!forum/tcmaker">Google Groups</a></li>
          <li><a href="https://twitter.com/tcmaker">Twitter</a></li>
        </ul>
      </div>

      <div class="col-md-3">
        <p><%= image_tag('logo-white-text.svg') -%></p>
        <p>Copyright &copy; 2009&ndash;2018 Twin Cities Maker. <a
          href="https://creativecommons.org/licenses/by-nc-sa/3.0/us/">Some
          rights reserved.</a></p>
        <ul class="list-unstyled">
          <li><a href="">Policies and Rules</a></li>
          <li><a href="">501(c)(3) Tax Information</a></li>
        </ul>
      </div>
    </div>
  </div>
  </div>
</footer>

app/views/layouts/partials/_head.html.erb
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Favicon, etc -->
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <title>Twin Cities Maker</title>
</head>

app/views/layouts/partials/dashboard/_topnav.html.haml
%nav.navbar.navbar-dark.fixed-top.bg-dark.navbar-expand-lg
  .navbar-brand
    = link_to('/dashboard') do
      = image_tag('logo-white-text.svg', class: "d-inline-block align-top", alt: "Twin Cities Maker")
  %button.navbar-toggler{ type: 'button', data: { toggle: 'collapse', target: '#navbarSupportedContent' }, aria: { controls: 'navbarSupportedContent', expanded: 'false', label: 'Toggle navigation' } }
    %span.navbar-toggler-icon

  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item
        = link_to 'Events', dashboard_events_path, class: 'nav-link'
      %li.nav-item
        = link_to 'Members', dashboard_members_path, class: 'nav-link'
      %li.nav-item
        = link_to 'Profile', dashboard_members_path, class: 'nav-link'

      %li.nav-item.active
        = link_to('#', class: 'nav-link') do
          Active
          %span.sr-only (current)
      %li.nav-item.disabled
        = link_to 'Disabled', '#', class: 'nav-link'

    %ul.navbar-nav.ml-auto
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{ href: '#', role: 'button', data: { toggle: 'dropdown' }, aria: { toggle: 'dropdown', haspopup: true, expanded: false } }
          = current_member ? current_member.full_name : Member.first.full_name
        .dropdown-menu{ 'aria-labelledby': 'navbarDropdown' }
          = link_to 'Action', '#', class: 'dropdown-item'
          = link_to 'Action', '#', class: 'dropdown-item'
          .dropdown-divider
          = link_to('Logout', destroy_member_session_path, class: 'dropdown-item', method: :delete)